### ISSUE TITLE
[Bug]: Omniauth missing client id, preventing sign in and signup using social auths

### ISSUE THREAD

**Issue by khairulhaaziq** [petakopi/petakopi.my#128]
# [Bug]: Omniauth missing client id, preventing sign in and signup using social auths

Im unable to signup or signin using social auths

<img width="639" alt="Screenshot 2024-01-10 at 8 11 51 PM" src="https://github.com/petakopi/petakopi.my/assets/101852870/8cd26072-bd9d-4d97-92a4-01d9b015bdd4">

<img width="696" alt="Screenshot 2024-01-10 at 8 15 14 PM" src="https://github.com/petakopi/petakopi.my/assets/101852870/50811d9c-11ea-4246-852d-f4565a499f4a">

**Comment by amree** [comment]
Acknowledging first. FB a known bug and it is because I didn't update my Privacy Policy and Terms & Conditions
