### ISSUE TITLE
[Feature Request]: Allow user to unselect filter tags to viewing all cafes

### ISSUE THREAD

**Issue by foohwa** [petakopi/petakopi.my#164]
**Description:**

It would be great to have a feature that allows users to unselect filter tags on the map interface. This would enable users to view all cafes without any filters applied.

**Steps to reproduce:**

	1.	Open the Live Map page.
	2.	Select any filter tag (e.g., “Early Bird,” “Night Owl,” “Halal Certified”).
	3.	Notice that there’s no option to unselect or deselect the tag to revert to viewing all cafes.

**Expected behavior**:

Users should be able to click on an active filter tag to unselect it, allowing them to view all cafes without any filters applied.

**Additional context:**

Screenshot attached for reference.
<img width="985" alt="image" src="https://github.com/user-attachments/assets/e5b1b10f-68e5-423f-9554-c3cc8760f5b7">

**Comment by amree** [comment]
Not the best solution. But it works. TBH, the whole map page requires a redesign as adding more options will help users but they will make the page 'messier'.

Thanks for the taking the effort to create this issue, really appreciate it.

![image](https://github.com/user-attachments/assets/d4fbf0b7-4a0d-4f44-b543-1bafc8c6f553)

**Comment by foohwa** [comment]
Tested it out on live server, I think its good enough for now! Thanks for the quick fix tho 😁

As for the options, probably you have a filter icon button on the right side, once user click, it will pop up a dialog that show all the options there, then user can toggle on and off for each options. I am not sure how hard is it to implement this on rails tho 🤣

**Comment by amree** [comment]
Agree on the suggestions. It's possible to do that and the interaction will mostly done using JS. It's quite similar to what we have on the front page where we have the "filter" concepts.

Ideally, both pages should have the same search. It's just the output is different 1) List of results 2) A map
